import Head from 'next/head';
import './globals.css';
import AppStateProvider from './hooks/UserState';

export const metadata = {
  title: 'Cursos',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode; title: string }) {
  return (
    <html lang="es">
      <body>
        <AppStateProvider>{children}</AppStateProvider>
      </body>
    </html>
  );
}
