import './globals.css';
import AppStateProvider from './hooks/UserState';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body>
        <AppStateProvider>
          {children}
        </AppStateProvider>
      </body>
    </html>
  );
}
